## Array 1D


In [6]:
import numpy as np

l = [1,2,3,4,5]

x = np.array(l)

print(f'Array l = {l}')
print(f'Array X = {x}')
print(f'Schape = {x.shape}')



Array l = [1, 2, 3, 4, 5]
Array X = [1 2 3 4 5]
Schape = (5,)


## Array 2D

In [12]:
l2 = [[1,2,3],[3,2,1]]

x2 = np.array(l2)

print(f'Array X2 = \n{x2}')
print(f'Schape = {x2.shape}')

Array X2 = 
[[1 2 3]
 [3 2 1]]
Schape = (2, 3)


## numpy.zeros()  e   numpy.ones()

In [13]:
linha_colunas = (2,4)

matriz_false = np.zeros(linha_colunas, dtype=int)

print(f'Array = \n{matriz_false}')
print(f'Schape = {matriz_false.shape}')

matriz_ture = np.ones(linha_colunas, dtype=int)

print(f'Array = \n{matriz_ture}')
print(f'Schape = {matriz_ture.shape}')

Array = 
[[0 0 0 0]
 [0 0 0 0]]
Schape = (2, 4)
Array = 
[[1 1 1 1]
 [1 1 1 1]]
Schape = (2, 4)


## np.linspace()

In [14]:
x_min, x_max = 5, 9

lin_matriz = np.linspace(x_min,x_max,6)

print(f'Array = \n{lin_matriz}')
print(f'Schape = {lin_matriz.shape}')

Array X = 
[5.  5.8 6.6 7.4 8.2 9. ]
Schape = (6,)


## np.eye()
#### gera uma matriz **identidade** 

In [15]:
ident = np.eye(5)

print(f'Array = \n{ident}')
print(f'Schape = {ident.shape}')

Array X = 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Schape = (5, 5)


## np.random.random()

In [17]:
rand = np.random.random(size=(2,3))

print(f'Array = \n{rand}')
print(f'Schape = {rand.shape}')

Array = 
[[0.14457305 0.05246861 0.72326514]
 [0.33739374 0.15469177 0.6833135 ]]
Schape = (2, 3)
